In [1]:
%pylab inline
import sympy as sp
sp.init_printing()

Populating the interactive namespace from numpy and matplotlib


# Sadd, Exercise 1.6

Determine the components of the vector $b_i$ and matrix $a_{ij}$ given in Exercise 1-1 in a new coordinate system found through a rotation of $45^o$ ($\pi/4$ radians) about the $x_1$-axis. The rotation direction follows the positive sense presented in Example 1-2.

## Solution

$b'_i = Q_{ij} b_j$, $a'_{ij} = Q_{ip}Q_{jq}a_{pq}$

In [2]:
a, b = {}, {}
a['a'], b['a'] = array([[1, 1, 1], [0, 4, 2], [0, 1, 1]]), array([1, 0, 2])
a['b'], b['b'] = (array([[1, 2, 0], [0, 2, 1], [0, 4, 2]]), array([2, 1, 1]))
a['c'], b['c'] = array([[1, 1, 1], [1, 0, 2], [0, 1, 4]]), array([1, 1, 0])

In [3]:
theta = pi / 4
Q = array([[1, 0, 0], [0, cos(theta), sin(theta)], [0, -sin(theta), cos(theta)]])

### Part a

In [4]:
b_prime = dot(Q, b['a'])
b_prime

array([ 1.        ,  1.41421356,  1.41421356])

In [5]:
a_prime = dot(dot(Q, a['a']), Q.T)
a_prime

array([[  1.00000000e+00,   1.41421356e+00,   1.11022302e-16],
       [  0.00000000e+00,   4.00000000e+00,  -1.00000000e+00],
       [  0.00000000e+00,  -2.00000000e+00,   1.00000000e+00]])

### Part b

In [6]:
b_prime = dot(Q, b['b'])
b_prime

array([  2.00000000e+00,   1.41421356e+00,   1.11022302e-16])

In [7]:
a_prime = dot(dot(Q, a['b']), Q.T)
a_prime

array([[ 1.        ,  1.41421356, -1.41421356],
       [ 0.        ,  4.5       , -1.5       ],
       [ 0.        ,  1.5       , -0.5       ]])

### Part c

In [8]:
b_prime = dot(Q, b['c'])
b_prime

array([ 1.        ,  0.70710678, -0.70710678])

In [9]:
a_prime = dot(dot(Q, a['c']), Q.T)
a_prime

array([[  1.00000000e+00,   1.41421356e+00,   1.11022302e-16],
       [  7.07106781e-01,   3.50000000e+00,   2.50000000e+00],
       [ -7.07106781e-01,   1.50000000e+00,   5.00000000e-01]])